export function generateScript(salt, roll) {
  const name = roll.species[0].toUpperCase() + roll.species.slice(1);
  const desc = [
    roll.rarity,
    roll.shiny ? "shiny" : "",
    roll.species,
    roll.eye !== "\u00b7" ? `${roll.eye} eyes` : "",
    roll.hat !== "none" ? roll.hat : "",
  ].filter(Boolean).join(" ");

  const personality = `You are ${name}, a ${desc} companion.`;

  return `#!/bin/bash

# ${desc}
# Generated by claude-buddy-seed
# https://redaphid.github.io/claude-buddy-seed/

NAME=${JSON.stringify(name)}
PERSONALITY=${JSON.stringify(personality)}
SALT=${JSON.stringify(salt)}

DIR="$HOME/.local/share/claude/versions"
BIN="$DIR/$(ls "$DIR" | grep '^[0-9]' | grep -v backup | grep -v pristine | sort | tail -1)"

[ ! -f "$BIN.pristine" ] && cp "$BIN" "$BIN.pristine"

tmp=$(mktemp "$DIR/patched.XXXXXX")
cp "$BIN.pristine" "$tmp"
perl -pi -0777 -e "s/friend-2026-401/$SALT/g" "$tmp"
codesign -s - --force "$tmp" 2>/dev/null
mv "$tmp" "$BIN"

CONF="$HOME/.claude.json"
tmp=$(mktemp)
jq --arg name "$NAME" --arg personality "$PERSONALITY" '
  .companion = {
    name: $name,
    personality: $personality,
    hatchedAt: (.companion.hatchedAt // now | floor)
  } | del(.companionMuted)
' "$CONF" > "$tmp" && mv "$tmp" "$CONF"
`;
}
