export function generateScript(salt, roll) {
  const desc = [
    roll.rarity,
    roll.shiny ? "shiny" : "",
    roll.species,
    roll.eye !== "\u00b7" ? `${roll.eye} eyes` : "",
    roll.hat !== "none" ? roll.hat : "",
  ].filter(Boolean).join(" ");

  return `#!/usr/bin/env node

// ${desc}
// Generated by claude-buddy-seed
// https://redaphid.github.io/claude-buddy-seed/

import { readFileSync, writeFileSync, copyFileSync, existsSync, readdirSync } from "fs"
import { join } from "path"
import { homedir } from "os"
import { execSync } from "child_process"

const replaceAll = (buf, needle, replacement) => {
  let i = 0
  while ((i = buf.indexOf(needle, i)) !== -1) { replacement.copy(buf, i); i += needle.length }
}

const buddyId = Buffer.from(${JSON.stringify(salt)})
const original = Buffer.from("friend-2026-401")
const claudesPath = join(homedir(), ".local", "share", "claude", "versions")
const latestPath = join(claudesPath, readdirSync(claudesPath).filter(f => /^\\d/.test(f) && !f.includes("backup") && !f.includes("pristine")).sort().at(-1))
const pristinePath = \`\${latestPath}.pristine\`

if (!existsSync(pristinePath) || readFileSync(latestPath).includes(original)) copyFileSync(latestPath, pristinePath)

const data = readFileSync(pristinePath)
replaceAll(data, original, buddyId)
writeFileSync(latestPath, data)
execSync(\`codesign -s - --force "\${latestPath}" 2>/dev/null\`)

const conf = join(homedir(), ".claude.json")
const cfg = JSON.parse(readFileSync(conf, "utf-8"))
delete cfg.companion
delete cfg.companionMuted
writeFileSync(conf, JSON.stringify(cfg, null, 2) + "\\n")
`;
}
