export function generateScript(salt, roll) {
  const desc = [
    roll.rarity,
    roll.shiny ? "shiny" : "",
    roll.species,
    roll.eye !== "·" ? `${roll.eye} eyes` : "",
    roll.hat !== "none" ? roll.hat : "",
  ].filter(Boolean).join(" ");

  return `#!/usr/bin/env node

// Standalone patcher — restores your buddy (${desc})
// No dependencies. Save to ~/.local/bin/puck
// Generated by claude-buddy-seed

import { readFileSync, writeFileSync, existsSync, copyFileSync, realpathSync, statSync, readdirSync, accessSync, constants } from "fs";
import { join } from "path";
import { homedir, platform } from "os";
import { execFileSync, execSync } from "child_process";

const TARGET_SALT = ${JSON.stringify(salt)};
const ORIGINAL_SALT = "friend-2026-401";
const SALT_LEN = ORIGINAL_SALT.length;

function findBinary() {
  const override = process.env.CLAUDE_BINARY_PATH?.trim();
  if (override && existsSync(override)) return override;

  try {
    const paths = execFileSync("which", ["-a", "claude"], { encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] })
      .split("\\n").map(p => p.trim()).filter(Boolean);
    for (const p of paths) {
      try {
        const resolved = realpathSync(p);
        if (existsSync(resolved) && statSync(resolved).size > 1_000_000) return resolved;
      } catch {}
    }
  } catch {}

  const versionsDir = join(homedir(), ".local", "share", "claude", "versions");
  if (existsSync(versionsDir)) {
    const versions = readdirSync(versionsDir).filter(f => !f.includes(".backup")).sort();
    if (versions.length > 0) return join(versionsDir, versions[versions.length - 1]);
  }

  return null;
}

function findCurrentSalt(data) {
  if (data.includes(Buffer.from(ORIGINAL_SALT))) return ORIGINAL_SALT;
  if (data.includes(Buffer.from(TARGET_SALT))) return TARGET_SALT;

  const text = data.toString("latin1");
  const patterns = [
    new RegExp(\`x{\${SALT_LEN - 8}}\\\\d{8}\`, "g"),
    new RegExp(\`friend-\\\\d{4}-.{\${SALT_LEN - 12}}\`, "g"),
  ];
  for (const pat of patterns) {
    let m;
    while ((m = pat.exec(text)) !== null) {
      if (m[0].length === SALT_LEN) return m[0];
    }
  }
  return null;
}

function clearCompanion() {
  const paths = [
    join(process.env.CLAUDE_CONFIG_DIR ?? join(homedir(), ".claude"), ".config.json"),
    join(homedir(), ".claude.json"),
  ];
  for (const p of paths) {
    if (!existsSync(p)) continue;
    try {
      const raw = readFileSync(p, "utf-8");
      const config = JSON.parse(raw);
      if (!config.companion && !config.companionMuted) continue;
      delete config.companion;
      delete config.companionMuted;
      const indent = raw.match(/^(\\s+)"/m)?.[1] ?? "  ";
      writeFileSync(p, JSON.stringify(config, null, indent) + "\\n");
      return p;
    } catch {}
  }
  return null;
}

const binaryPath = findBinary();
if (!binaryPath) { console.error("\\u2717 Claude binary not found"); process.exit(1); }

const data = readFileSync(binaryPath);
const currentSalt = findCurrentSalt(data);
if (!currentSalt) { console.error("\\u2717 Could not find salt in binary"); process.exit(1); }

if (currentSalt === TARGET_SALT) {
  console.log("\\u2713 Already patched");
  process.exit(0);
}

try { accessSync(binaryPath, constants.W_OK); } catch {
  console.error(\`\\u2717 \${binaryPath} is not writable\`);
  process.exit(1);
}

const backupPath = binaryPath + ".backup";
if (!existsSync(backupPath)) {
  copyFileSync(binaryPath, backupPath);
  console.log(\`  backup \\u2192 \${backupPath}\`);
}

const oldBuf = Buffer.from(currentSalt);
const newBuf = Buffer.from(TARGET_SALT);
let count = 0, idx = 0;
while (true) {
  idx = data.indexOf(oldBuf, idx);
  if (idx === -1) break;
  newBuf.copy(data, idx);
  count++;
  idx += newBuf.length;
}

if (count === 0) { console.error(\`\\u2717 Salt "\${currentSalt}" not found in binary data\`); process.exit(1); }
writeFileSync(binaryPath, data);
console.log(\`  patched \${count} occurrence(s) in \${binaryPath}\`);

if (platform() === "darwin") {
  try { execSync(\`codesign -s - --force "\${binaryPath}" 2>/dev/null\`); console.log("  re-signed (ad-hoc)"); } catch {}
}

const cleared = clearCompanion();
if (cleared) console.log(\`  cleared companion cache in \${cleared}\`);

console.log("\\u2713 Done. Restart Claude and run /buddy.");
`;
}
